zn.define([
    './AdminUser',
    './Brand',
    './Detail',
    './My',
    './Project',
    './ProjectDetail',
    './RegionProject',
    './Shop',
    './SMS',
    './Supplier',
    './SupplierOrder',
    './Task',
    './User',
    './Var'
]);
